---
title: "Bioensayo muestra externa SargaPower y Exuroot líquido 01/mar/24"
output: html_notebook
---


```{r}
# Librerias
library(dplyr)
library(tidyr) 
library(readr) 
library(udunits2)
library(tidyverse)
library(car)
library(agricolae)
library(tidyverse)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(ggbreak)
library(plotrix)
library(ggsignif)
library(wesanderson)
library(paletteer)
```


```{r}
# Archivo
sarga <- read.csv("~/RStudio/CursoInnovak/Agronomia/Materiales/Bioensayo sargapower_exurootL_01mar24.csv")
Longitud <- read.csv("~/RStudio/CursoInnovak/Agronomia/Materiales/Longitud sargapower 01mar.csv")
Laterales <- read.csv("~/RStudio/CursoInnovak/Agronomia/Materiales/Laterales sargapower 01mar.csv")

```


# Graficos del promedio de la longitud de raiz y raices lateriales para Hidrolizado de Ruezno 

```{r}
# Filtrar datos para solo obtener una tabla de los promedios de la longitud de raiz: 

Promedios_long <- Longitud %>%
  group_by(Tratamiento) %>%
  summarize(Longitud = mean(Longitud, na.rm = TRUE))

Promedios_lat <- Laterales %>%
  group_by(Tratamiento) %>%
  summarize(Laterales = mean(ifelse(Laterales==0, NA, Laterales), na.rm = TRUE))


# Se acomodan los datos: 
levels(Promedios_long$Tratamiento)
Promedios_long$Tratamiento=factor(Promedios_long$Tratamiento,levels=c("Control","NAA","GA3","Exuroot D","Exuroot 1:20","Exuroot 1:50","SargaPower D","SargaPower 1:20","SargaPower 1:50"))
levels(Promedios_long$Tratamiento)

# Graficos de la longitud de raiz 
ggplot(Promedios_long)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Longitud, fill= Tratamiento))+
  ggtitle("Bioensayo SargaPower y Exuroot")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Longitud de raíz primaria")+
  theme(axis.text.x = element_text(angle=45,hjust=1,size = 12))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#0F6B99", "#0F6B99","#0F6B99","#A3CC51" ,"#A3CC51","#A3CC51"))+
  theme(legend.position = "none")
  

```

```{r}

# Graficos de raices lateriales 

# Se acomodan los datos: 
levels(Promedios_lat$Tratamiento)
Promedios_lat$Tratamiento=factor(Promedios_lat$Tratamiento,levels=c("Control","NAA","GA3","Exuroot D","Exuroot 1:20","Exuroot 1:50","SargaPower D","SargaPower 1:20","SargaPower 1:50"))
levels(Promedios_lat$Tratamiento)


ggplot(Promedios_lat)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Laterales, fill=Tratamiento))+
  ggtitle("Bioensayo SargaPower y Exuroot")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#0F6B99", "#0F6B99","#0F6B99","#A3CC51" ,"#A3CC51","#A3CC51"))+
  theme(legend.position = "none")


```

```{r}
# Ambas variables en un mismo grafico 

Promedios <- sarga %>%
  group_by(Tratamiento, Variable) %>%
  summarize(Resultado = mean(ifelse(Resultado==0, NA, Resultado), na.rm = TRUE))


ggplot(Promedios, aes(x = Tratamiento, y = Resultado, fill = Variable))+
  theme_bw()+
  geom_col(position = "dodge")+
  ggtitle("Bioensayo de SargaPower y Exuroot L")+
  theme(plot.title = element_text(hjust = 0.5, size = 19, color= "black", face = "bold"))+
  ylab("Resultados")+
  scale_x_discrete(limits = c("Control","NAA","GA3","Exuroot D","Exuroot 1:20","Exuroot 1:50","SargaPower D","SargaPower 1:20","SargaPower 1:50"))+
  theme(axis.text.x = element_text(angle=45,hjust=1,size = 13))+
  theme(axis.text.y = element_text(size = 13))+
  theme(axis.title.x = element_text(size = 15))+
  theme(axis.title.y = element_text(vjust = 3,size = 15))+
  scale_fill_manual(name = "Variable",values = c("#A3CC51","#0F6B99"))
```

