---
title: "Bioensayo Muestras Externas y ECA´s Lote 2"
output: html_notebook
---

```{r}
#Librerias 
library(dplyr)
library(tidyr) 
library(readr) 
library(udunits2)
library(tidyverse)
library(car)
library(agricolae)
library(tidyverse)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(ggbreak)
library(plotrix)
library(ggsignif)
library(wesanderson)
library(paletteer)

```

LOTE 2 del bioensayo de muestras externas de Humik y ECA´s maduro y sin madurar en polvo (exuroot)...

```{r}
# archivos 
Muestras <- read.csv("~/Rstudio/CursoInnovak/Agronomia/Materiales/Bioensayo Mat_Externos_ECA_L2_05Mar24.csv")
Variables <- read.csv("~/RStudio/CursoInnovak/Agronomia/Materiales/Bioensayo Mat_Externos_ECA_L2_Variables_05Mar24.csv")
```

# Graficos del promedio de la longitud de raiz y raices lateriales para el lote 2 de las muestras externas de Humik y exuroot eca´s maduro y sin madurar polvo

```{r}
# Filtrar datos para solo obtener una tabla de los promedios de la longitud de raiz: 

Promedios <- Muestras %>%
  group_by(Tratamiento) %>%
  summarize(Long = mean(Longitud, na.rm = TRUE),
            Lat = mean(ifelse(Laterales==0, NA, Laterales), na.rm = TRUE))


# Se acomodan los datos: 
levels(Promedios$Tratamiento)
Promedios$Tratamiento=factor(Promedios$Tratamiento,levels=c("Control","NAA","GA3","WSG directo","WSG 1:20","WSG 1:50", "WSP directo", "WSP 1:20", "WSP 1:50", "ONE directo", "ONE 1:20", "ONE 1:50", "GROW directo", "GROW 1:20", "GROW 1:50", "ECA M directo", "ECA M 1:20", "ECA M 1:50", "ECA S/M directo", "ECA S/M 1:20", "ECA S/M 1:50"))
levels(Promedios$Tratamiento)

# Graficos de la longitud de raiz 
ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long, fill=Tratamiento))+
  ggtitle("Bioensayo Muestras externas Humik y ECA´s exuroot M y S/M (05Mar24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, color = "black", face = "bold"))+
  ylab("Longitud de raíz primaria")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#cc3399","#d65cad","#ebadd7","#ff8080","#ff4d4d","#ff3333","#e67300","#ff9933","#ffb366","#ffd633","#ffcc00","#e6b800","#86b300","#ace600","#c6ff1a","#ffbb33" ,"#ffaa00","#b37700"))+
  theme(legend.position = "none")


```


```{r}
# Graficos de raices lateriales 

ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat, fill=Tratamiento))+
  ggtitle("Bioensayo Muestras externas Humik y ECA´s exuroot M y S/M (05Mar24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#cc3399","#d65cad","#ebadd7","#ff8080","#ff4d4d","#ff3333","#e67300","#ff9933","#ffb366","#ffd633","#ffcc00","#e6b800","#86b300","#ace600","#c6ff1a","#ffbb33" ,"#ffaa00","#b37700"))+
  theme(legend.position = "none")
```
```{r}
# Ambas variables en un mismo grafico 

Promedios_v <- Variables %>%
  group_by(Tratamiento, Variable) %>%
  summarize(Resultado = mean(ifelse(Resultado==0, NA, Resultado), na.rm = TRUE))


ggplot(Promedios_v, aes(x = Tratamiento, y = Resultado, fill = Variable))+
  theme_bw()+
  geom_col(position = "dodge")+
  ggtitle("Bioensayo Muestras externas Humik y ECA´s exuroot M y S/M (05Mar24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, color= "black", face = "bold"))+
  ylab("Resultados")+
  scale_x_discrete(limits = c("Control","NAA","GA3","WSG directo","WSG 1:20","WSG 1:50", "WSP directo", "WSP 1:20", "WSP 1:50", "ONE directo", "ONE 1:20", "ONE 1:50", "GROW directo", "GROW 1:20", "GROW 1:50", "ECA M directo", "ECA M 1:20", "ECA M 1:50", "ECA S/M directo", "ECA S/M 1:20", "ECA S/M 1:50"))+
  theme(axis.text.x = element_text(angle=45,hjust=1,size = 9))+
  theme(axis.text.y = element_text(size = 13))+
  theme(axis.title.x = element_text(size = 13, vjust = -1.5))+
  theme(axis.title.y = element_text(vjust = 3,size = 13))+
  scale_fill_manual(name = "Variable",values = c("#A3CC51","#0F6B99"))
```

