---
title: "Muestras externas y ECA´s 15/Feb/24"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr) 
library(readr) 
library(udunits2)
library(tidyverse)
library(car)
library(agricolae)
library(tidyverse)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(ggbreak)
library(plotrix)
library(ggsignif)
library(wesanderson)
library(paletteer)
```
```{r}
# Archivos:
Bioensayo <- read.csv("~/RStudio/CursoInnovak/Agronomia/Materiales/Bioensayo Mat_Externos_ECA_15Feb24.csv")

```



# Graficos del promedio de la longitud de raiz y raices laterales para Muestras Externas y ECA´s 

```{r}
# Filtrar datos para solo obtener una tabla de los promedios de la longitud de raiz para el lote 1 y 2: 

Promedios <- Bioensayo %>%
  group_by(Tratamiento) %>%
  summarize(Long = mean(Longitud, na.rm = TRUE),
            Lat = mean(ifelse(Laterales==0, NA, Laterales), na.rm = TRUE))


# Se acomodan los datos: 
levels(Promedios$Tratamiento)
Promedios$Tratamiento=factor(Promedios$Tratamiento,levels=c("Control","NAA","GA3","Humik WSG directo","Humik WSG 1:20", "Humik WSG 1:50","Humik WSP directo","Humik WSP 1:20","Humik WSP 1:50","Humik ONE directo","Humik ONE 1:20","Humik ONE 1:50","Ful-Grow Gold 2x directo","Ful-Grow Gold 2x 1:20","Ful-Grow Gold 2x 1:50","ECA Maduro directo","ECA Maduro 1:20","ECA Maduro 1:50","ECA S/M directo","ECA S/M 1:20","ECA S/M 1:50"))
levels(Promedios$Tratamiento)

# Graficos de la longitud de raiz 
ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long, fill=Tratamiento))+
  ggtitle("Bioensayo Muestras Externas y ECA´s")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Longitud de raíz primaria")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  theme(legend.position = "none")

# Graficos de raices lateriales lote 1 
ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat, fill=Tratamiento))+
  ggtitle("Bioensayo Muestras Externas y ECA´s")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  theme(legend.position = "none")



```

