---
title: "Repetición Nebiol y extractos 09/feb/24"
output: html_notebook
---


```{r}
# Librerias
library(dplyr)
library(tidyr) 
library(readr) 
library(udunits2)
library(tidyverse)
library(car)
library(agricolae)
library(tidyverse)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(ggbreak)
library(plotrix)
library(ggsignif)
library(wesanderson)
library(paletteer)

```

```{r}
# Archivos para ambos lotes:
Longitud <- read.csv("~/RStudio/CursoInnovak/Agronomia/Materiales/Longitud nebiol rep M1-M6.csv")

Laterales <- read.csv("~/RStudio/CursoInnovak/Agronomia/Materiales/Laterales nebiol rep M1-M6.csv")

# Archivo para los grarficos separados 
Bioensayo <- read.csv("~/RStudio/CursoInnovak/Agronomia/Materiales/Bioensayo_rep_M1-M6_long_(lote1,2,3).csv")

```

# Graficos del promedio de la longitud de raiz y raices lateriales para Nebiol y extractos M1-M6

```{r}
# Filtrar datos para solo obtener una tabla de los promedios de la longitud de raiz para el lote 1 y 2: 

Promedios <- Bioensayo %>%
  group_by(Tratamiento) %>%
  summarize(Long_lote1 = mean(Longitud.lote.1, na.rm = TRUE),
            Long_lote2 = mean(Longitud.lote.2, na.rm = TRUE),
            Long_lote3 = mean(Longitud.lote.3, na.rm = TRUE),
            Lat_lote1 = mean(ifelse(Laterales.lote.1==0, NA, Laterales.lote.1), na.rm = TRUE),
            Lat_lote2 = mean(ifelse(Laterales.lote.2==0, NA, Laterales.lote.2), na.rm = TRUE),
            Lat_lote3 = mean(ifelse(Laterales.lote.3==0, NA, Laterales.lote.3), na.rm = TRUE))


# Se aocmodan los datos: 
levels(Promedios$Tratamiento)
Promedios$Tratamiento=factor(Promedios$Tratamiento,levels=c("Control","NAA","GA3","M1 Directo", "M1 1:20","M1 1:50","M2 Directo", "M2 1:20","M2 1:50","M3 Directo","M3 1:20","M3 1:50", "M4 Directo","M4 1:20","M4 1:50", "M5 Directo", "M5 1:20", "M5 1:50", "M6 Directo", "M6 1:20", "M6 1:50"))
levels(Promedios$Tratamiento)

# Graficos de la longitud de raiz lote 1 
ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long_lote1, fill=Tratamiento))+
  ggtitle("Bioensayo de muestras de Nebiol y Extractos Lote #1 (17/enero/24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Longitud de raíz primaria")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"),labels = c("Control","NAA","GA3","Pasta","Pasta","Pasta","B_Fenol","B_Fenol","B_Fenol","Extracto Ruezno","Extracto Ruezno","Extracto Ruezno","Extracto Agave","Extracto Agave","Extracto Agave","Extracto Caña","Extracto Caña","Extracto Caña","Pasta + Fenol","Pasta + Fenol","Pasta + Fenol"))

# Graficos de raices lateriales lote 1 
ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat_lote1, fill=Tratamiento))+
  ggtitle("Bioensayo de muestras de NEBIOL y extractos Lote #1")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  theme(legend.position = "none")


# Graficos de la longitud de raiz lote 2 
ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long_lote2, fill=Tratamiento))+
  ggtitle("Bioensayo de muestras de NEBIOL y extractos Lote #2")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Longitud de raíz primaria")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  theme(legend.position = "none")


# Graficos de raices lateriales lote 2 
ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat_lote2, fill=Tratamiento))+
  ggtitle("Bioensayo de muestras de NEBIOL y extractos Lote #2")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  theme(legend.position = "none")


# Graficos de la longitud de raiz lote 3 
ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long_lote3, fill=Tratamiento))+
  ggtitle("Bioensayo de muestras de NEBIOL y extractos Lote #3")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Longitud de raíz primaria")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  theme(legend.position = "none")

# Graficos de raices lateriales lote 3 
ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat_lote3, fill=Tratamiento))+
  ggtitle("Bioensayo de muestras de Nebiol y Extractos Lote #3")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  theme(legend.position = "none")



# Para presentar los graficos se uniran el lote 1 y el lote 2 rep (3)
# Graficos de la longitud de raiz lote 1 
Graf_long1 <- ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long_lote1, fill=Tratamiento))+
  ggtitle("Bioensayo muestras de Nebiol y Extractos Lote #1 (17/ene/24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Longitud de raíz primaria")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  theme(legend.position = "none")

# Graficos de la longitud de raiz lote 3 (rep del 2)
Graf_long3 <- ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long_lote3, fill=Tratamiento))+
  ggtitle("Bioensayo muestras de Nebiol y Extractos Lote #2 (09/feb/24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Longitud de raíz primaria")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  theme(legend.position = "none")


# Graficos de raices lateriales lote 1 
Graf_lat1 <- ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat_lote1, fill=Tratamiento))+
  ggtitle("Bioensayo muestras de Nebiol y Extractos Lote #1 (17/ene/24")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  theme(legend.position = "none")

# Graficos de raices lateriales lote 3 (rep del 2)
Graf_lat3 <- ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat_lote3, fill=Tratamiento))+
  ggtitle("Bioensayo muestras de Nebiol y Extractos Lote #2 (17/ene/24")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  theme(legend.position = "none")

Graf_long1|Graf_long3
Graf_lat1|Graf_lat3
```

```{r}
# Ambos lotes en un mismo grafico para la variable de la longitud de raiz: 
Prom <- Longitud %>%
  group_by(Tratamiento, Lote) %>%
  summarize(Longitud = mean(Longitud, na.rm = TRUE))
 
ggplot(Prom, aes(x = Tratamiento, y = Longitud, fill = Lote))+
  theme_bw()+
  geom_col(position = "dodge")+
  ggtitle("Bioensayo de muestras de NEBIOL y extractos")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color= "black", face = "bold"))+
  ylab("Longitud de raíz primaria")+
  scale_x_discrete(limits = c("Control","NAA","GA3","M1 Directo", "M1 1:20","M1 1:50","M2 Directo", "M2 1:20","M2 1:50","M3 Directo","M3 1:20","M3 1:50", "M4 Directo","M4 1:20","M4 1:50", "M5 Directo", "M5 1:20", "M5 1:50", "M6 Directo", "M6 1:20", "M6 1:50"))+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y = element_text(vjust = 3))+
  scale_fill_manual(name = "# Lote",values = c("#00688B", "seagreen3","#68228B"))


# Ambos lotes en un mismo grafico para la varialbe de raices laterales:
Promlat <- Laterales %>%
  group_by(Tratamiento, Lote) %>%
  summarize(Media_laterales= mean(ifelse(Raices.laterales==0, NA, Raices.laterales), na.rm = TRUE))
 
ggplot(Promlat, aes(x = Tratamiento, y = Media_laterales, fill = Lote))+
  geom_col( position = "dodge")+
  theme_bw()+
  ggtitle("Bioensayo de muestras de NEBIOL y extractos")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  scale_x_discrete(limits = c("Control","NAA","GA3","M1 Directo", "M1 1:20","M1 1:50","M2 Directo", "M2 1:20","M2 1:50","M3 Directo","M3 1:20","M3 1:50", "M4 Directo","M4 1:20","M4 1:50", "M5 Directo", "M5 1:20", "M5 1:50", "M6 Directo", "M6 1:20", "M6 1:50"))+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y = element_text(vjust =3))+
  scale_fill_manual(name = "# Lote", values = c("#00688B", "seagreen3","#68228B"))

```